// packages/vue/src/autocomplete/src/autocomplete.vue
<template>
  <div
    ref="reference"
    class="company-autocomplete"
    :class="[
      {
        'company-autocomplete--show-submit': showSubmitButton,
        'company-autocomplete--words': nativeInputValue.length > 0,
        'company-autocomplete--activated': suggestionVisible,
      },
    ]"
    v-click-outside="handleClickOutside"
    @keydown="handleKeyDown"
  >
    <div class="company-autocomplete__input">
      <input
        ref="input"
        type="text"
        v-bind="$attrs"
        :placeholder="placeholder"
        @input="handleInput"
        @click="handleInputClick"
        @focus="handleInputFocus"
        @blur="handleInputBlur"
      />
      <div v-if="clearable" class="company-autocomplete__clear">
        <i class="company-autocomplete__clear-icon" @click="handleInputClear" v-html="clearIcon" />
      </div>
    </div>
    <div v-if="showSubmitButton" class="company-autocomplete__submit">
      <button type="button" @click="handleSubmit">
        {{ submitButtonLabel }}
      </button>
    </div>
    <Teleport to="body" :disabled="!popupAppendToBody">
      <div
        ref="floating"
        class="suggestion-popper"
        :class="[
          {
            'suggestion-popper--activated': suggestionVisible,
          },
        ]"
        :style="floatingStyles"
      >
        <div class="suggestion-popper__body">
          <div
            class="suggestion"
            v-for="(item, index) in suggestions"
            :key="`${item.name}-${index}`"
            @click="handleSuggestionClick(item)"
            :class="[
              {
                'suggestion--keyboard-active': keyboardActiveIndex === index,
              },
            ]"
          >
            <div class="suggestion__avatar">
              <i
                class="suggestion__avatar-icon"
                v-if="suggestionType === 'history'"
                v-html="historyItemIcon"
              />
              <img :alt="item.id" :src="item.avatar" v-else-if="item.avatar" />
            </div>
            <div class="suggestion__label">
              {{ item.name }}
            </div>
            <div class="suggestion__extra"></div>
          </div>
        </div>
        <div
          class="suggestion-popper__footer"
          v-show="historyClearable && suggestionType === 'history'"
        >
          <a href="javascript:;" @click="handleHistoryClear">
            <i class="suggestion-popper__icon" v-html="historyClearIcon" />
            删除历史
          </a>
        </div>
      </div>
    </Teleport>
  </div>
</template>

<script lang="ts">
  import { defineComponent, PropType, isVue2, isVue3, CSSProperties } from 'vue-demi';
  import { autocomplete } from '@company-ui/core';
  import { debounce, removeHtmlTags, isUndefined, isNil } from '@company-ui/shared';
  import { autoUpdate, computePosition, offset, size, flip } from '@floating-ui/vue';
  import clickOutside from '../../directives/click-outside';
  import Teleport from '../../teleport';

  const debounceQueryMethod = 'handleDebounceQuerySuggestion';

  export default defineComponent({
    name: 'Autocomplete',
    directives: {
      clickOutside,
    },
    ...(isVue2
      ? {
          components: {
            Teleport,
          },
          model: {
            prop: 'modelValue',
            event: 'modelChange',
          },
        }
      : null),
    props: {
      modelValue: {
        type: String,
        default: '',
      },
      api: {
        type: String as PropType<autocomplete.Type.ApiType>,
        default: 'clearbit',
      },
      queryDelay: {
        type: Number,
        default: 500,
      },
      placeholder: {
        type: String,
        default: '请输入企业名称或统一社会信用代码',
      },
      clearable: {
        type: Boolean,
        default: true,
      },
      backFill: {
        type: Boolean,
        default: false,
      },
      popupAppendToBody: {
        type: Boolean,
        default: true,
      },
      autoFocus: {
        type: Boolean,
        default: true,
      },
      showSubmitButton: {
        type: Boolean,
        default: true,
      },
      submitButtonLabel: {
        type: String,
        default: 'Submit',
      },
      offsetTop: {
        type: Number,
        default: 5,
      },
      autoFlip: {
        type: Boolean,
        default: false,
      },
      historyEnabled: {
        type: Boolean,
        default: true,
      },
      historyType: {
        type: String as PropType<autocomplete.Type.HistoryType>,
        default: 'localStorage',
      },
      historyStorageKey: {
        type: String,
        default: 'company-history',
      },
      historyClearable: {
        type: Boolean,
        default: true,
      },
    },
    emits: [
      isVue2 ? 'modelChange' : 'update:modelValue',
      'input',
      'fetch',
      'abortFetch',
      'select',
      'clear',
      'focus',
      'blur',
      'submit',
      'dropdownVisibleChange',
    ],
    data() {
      return {
        isVue3,
        abortController: undefined as AbortController | undefined,
        latestKeyword: '' as string,
        selectSuggestion: undefined as autocomplete.Type.CompanyDataType | undefined,
        suggestionVisible: false,
        suggestionType: 'fetch',
        suggestions: [] as autocomplete.Type.CompanyDataType[],
        keyboardActiveIndex: undefined as number | undefined,
        floatingWidth: undefined as string | undefined,
        floatingStyles: {
          left: '0',
          top: '0',
          width: 'auto',
        } as CSSProperties,
        clearIcon: autocomplete.initialOptions.clearIcon,
        historyClearIcon: autocomplete.initialOptions.history.clearIcon,
        historyItemIcon: autocomplete.initialOptions.history.itemIcon,
      };
    },
    computed: {
      nativeInputValue(): string {
        return isNil(this.modelValue) ? '' : String(this.modelValue);
      },
    },
    watch: {
      nativeInputValue() {
        this.setNativeInputValue();
      },
    },
    created() {
      this[debounceQueryMethod] = debounce(this.handleQuerySuggestion, this.queryDelay);
    },
    mounted() {
      if (this.autoFocus) {
        this.handleFocus();
      }
      this.setNativeInputValue();
      this.handleCalculatePosition();
    },
    methods: {
      handleFocus() {
        (this.$refs.input as HTMLInputElement).focus();
      },
      handleCalculatePosition() {
        const reference = this.$refs.reference as HTMLElement;
        const floating = this.$refs.floating as HTMLElement;
        autoUpdate(reference, floating, () => {
          computePosition(reference, floating, {
            middleware: [
              offset(this.offsetTop),
              size({
                apply: ({ rects }) => {
                  this.floatingStyles.width = `${rects.reference.width}px`;
                },
              }),
              ...(this.autoFlip
                ? [
                    flip({
                      fallbackPlacements: ['top'],
                    }),
                  ]
                : []),
            ],
          }).then(({ x, y }) => {
            this.floatingStyles.left = `${x}px`;
            this.floatingStyles.top = `${y}px`;
          });
        });
      },
      handleCancelQuerySuggestion() {
        if (this.abortController) {
          this.abortController.abort('repeated request');
          this.abortController = undefined;
        }
      },
      async handleQuerySuggestion(value: string) {
        this.handleCancelQuerySuggestion();
        if (this.nativeInputValue === this.latestKeyword) {
          this.showSuggestion();
          return;
        }
        this.abortController = new AbortController();
        autocomplete
          .handleQueryData(value.trim(), this.api as string, this.abortController)
          .then(({ data }) => {
            this.latestKeyword = value.trim();
            this.suggestions = data;
            this.showSuggestion();
            this.$emit('fetch', data);
          })
          .catch((e) => {
            if (e.name === 'AbortError') {
              this.$emit('abortFetch', e);
            }
          });
      },
      setNativeInputValue() {
        const input = this.$refs.input as HTMLInputElement;
        if (input.value === this.nativeInputValue) {
          return;
        }
        input.value = this.nativeInputValue;
      },
      handleInput(event: Event) {
        this.hideSuggestion();
        const { value } = event.target as HTMLInputElement;
        this.handleUpdateModelValue(value);
        this.$emit('input', value);
        this.keyboardActiveIndex = undefined;
        this.selectSuggestion = undefined;
        if (value.length === 0) {
          this.clearSuggestion();
          return;
        }
        this[debounceQueryMethod](value);
      },
      handleInputClick() {
        if (this.nativeInputValue) {
          this.handleQuerySuggestion(this.nativeInputValue);
        } else if (this.historyEnabled) {
          this.latestKeyword = '';
          this.handleShowHistory();
        }
      },
      handleInputFocus() {
        this.$emit('focus');
      },
      handleInputBlur() {
        this.handleCancelQuerySuggestion();
        this.$emit('blur');
      },
      handleShowHistory() {
        const options = {
          enabled: this.historyEnabled,
          key: this.historyStorageKey,
          type: this.historyType,
        };
        this.suggestions = autocomplete.getHistory(options as autocomplete.Type.HistoryOptions);
        this.showSuggestion('history');
      },
      clearSuggestion() {
        this.suggestions = [];
      },
      showSuggestion(type = 'fetch') {
        if (this.suggestions.length === 0) {
          this.clearSuggestion();
          this.hideSuggestion();
          return;
        }
        this.suggestionType = type;
        if (this.suggestionVisible) {
          return;
        }
        this.suggestionVisible = true;
        this.$emit('dropdownVisibleChange', true);
      },
      hideSuggestion() {
        if (!this.suggestionVisible) {
          return;
        }
        this.suggestionVisible = false;
        this.$emit('dropdownVisibleChange', false);
      },
      handleSubmit() {
        this.$emit('submit', {
          text: this.nativeInputValue,
        });
      },
      handleInputClear() {
        this.selectSuggestion = undefined;
        this.handleUpdateModelValue('');
        this.clearSuggestion();
        this.hideSuggestion();
        this.handleFocus();
        this.$emit('clear');
      },
      handleClickOutside() {
        this.hideSuggestion();
      },
      handleKeyDown(event: KeyboardEvent) {
        switch (event.key) {
          case 'Enter':
            if (!isUndefined(this.keyboardActiveIndex)) {
              this.handleSuggestionClick(this.suggestions[this.keyboardActiveIndex!]);
            }
            break;
          case 'ArrowUp':
            if (!this.keyboardActiveIndex) {
              this.keyboardActiveIndex = this.suggestions.length - 1;
            } else {
              this.keyboardActiveIndex--;
            }
            this.backFill && this.handleFillInput();
            break;
          case 'ArrowDown':
            if (
              isUndefined(this.keyboardActiveIndex) ||
              this.keyboardActiveIndex! >= this.suggestions.length - 1
            ) {
              this.keyboardActiveIndex = 0;
            } else {
              this.keyboardActiveIndex!++;
            }
            this.backFill && this.handleFillInput();
            break;
          case 'Escape':
            this.handleInputClear();
            break;
        }
      },
      handleFillInput() {
        this.selectSuggestion = this.suggestions[this.keyboardActiveIndex!];
        this.handleUpdateModelValue(removeHtmlTags(this.selectSuggestion!.name || ''));
      },
      handleHistoryClear() {
        const options = {
          key: this.historyStorageKey,
          type: this.historyType,
        };
        autocomplete.removeHistory(options as autocomplete.Type.HistoryOptions);
        this.clearSuggestion();
        this.hideSuggestion();
      },
      handleSuggestionClick(company: autocomplete.Type.CompanyDataType) {
        this.handleUpdateModelValue(removeHtmlTags(company.name));
        this.selectSuggestion = {
          id: company.id,
          name: company.name,
        };
        this.clearSuggestion();
        this.hideSuggestion();
        if (this.historyEnabled && this.selectSuggestion) {
          const options = {
            enabled: this.historyEnabled,
            key: this.historyStorageKey,
            type: this.historyType,
          };
          autocomplete.addHistory(
            this.selectSuggestion!,
            options as autocomplete.Type.HistoryOptions
          );
        }
        this.$emit('select', this.selectSuggestion);
      },
      handleUpdateModelValue(value: string) {
        if (isVue2) {
          this.$emit('modelChange', value);
        } else {
          this.$emit('update:modelValue', value);
        }
      },
    },
  });
</script>

// packages/react/src/autocomplete/index.tsx
import React, { useState, useRef, useEffect } from 'react';
import clsx from 'clsx';
import { useMount, useClickAway, useDebounceFn, useGetState, useControllableValue } from 'ahooks';
import { autocomplete } from '@company-ui/core';
import { isUndefined, removeHtmlTags } from '@company-ui/shared';
import { FloatingPortal, useFloating, autoUpdate, offset, size, flip } from '@floating-ui/react';

export type AutoCompleteProps = {
  defaultValue?: string;
  value?: string;
  api?: string;
  queryDelay?: number;
  placeholder?: string;
  clearable?: boolean;
  backFill?: boolean;
  popupAppendToBody?: boolean;
  autoFocus?: boolean;
  showSubmitButton?: boolean;
  submitButtonLabel?: string;
  offsetTop?: number;
  autoFlip?: boolean;
  historyEnabled?: boolean;
  historyType?: autocomplete.Type.HistoryType;
  historyStorageKey?: string;
  historyClearable?: boolean;
  onInput?: (_value: string) => void;
  onFetch?: (_data: autocomplete.Type.CompanyDataType[]) => void;
  onAbortFetch?: (_e: Error) => void;
  onSelect?: (_data: autocomplete.Type.CompanyDataType) => void;
  onClear?: () => void;
  onFocus?: () => void;
  onBlur?: () => void;
  onSubmit?: (_args: { text: string }) => void;
  onDropdownVisibleChange?: (_state: boolean) => void;
};

const SuggestionComponent = {
  default: React.Fragment,
  portal: FloatingPortal,
};

const AutoComponent: React.FC<AutoCompleteProps> = (props) => {
  const {
    api = 'clearbit',
    queryDelay = 500,
    placeholder = '请输入企业名称或统一社会信用代码',
    clearable = true,
    backFill = false,
    popupAppendToBody = true,
    autoFocus = true,
    showSubmitButton = true,
    submitButtonLabel = 'Submit',
    offsetTop = 5,
    autoFlip = false,
    historyEnabled = true,
    historyType = 'localStorage',
    historyStorageKey = 'company-history',
    historyClearable = true,
    onInput,
    onFetch,
    onAbortFetch,
    onSelect,
    onClear,
    onFocus,
    onBlur,
    onSubmit,
    onDropdownVisibleChange,
  } = props;

  const clearIcon = autocomplete.initialOptions.clearIcon;
  const historyClearIcon = autocomplete.initialOptions.history.clearIcon;
  const historyItemIcon = autocomplete.initialOptions.history.itemIcon;
  const Suggestion = SuggestionComponent[popupAppendToBody ? 'portal' : 'default'];

  const [inputValue, setInputValue] = useControllableValue<string>(props);
  const [abortController, setAbortController] = useState<AbortController>();
  const [latestKeyword, setLatestKeyword] = useState('');
  const [selectSuggestion, setSelectSuggestion] = useState<autocomplete.Type.CompanyDataType>();
  const [suggestionVisible, setSuggestionVisible] = useState(false);
  const [suggestionType, setSuggestionType] = useState('fetch');
  const [suggestions, setSuggestions, getSuggestions] = useGetState<
    autocomplete.Type.CompanyDataType[]
  >([]);
  const [keyboardActiveIndex, setKeyboardActiveIndex] = useState<number>();
  const [floatingFullStyles, setFloatingFullStyles] = useState<React.CSSProperties>();
  const input = useRef<HTMLInputElement>(null);
  const { refs, floatingStyles } = useFloating({
    whileElementsMounted: autoUpdate,
    middleware: [
      offset(offsetTop),
      size({
        apply: ({ rects }) => {
          setFloatingFullStyles((style) => ({
            ...style,
            width: `${rects.reference.width}px`,
          }));
        },
      }),
      ...(autoFlip ? [flip({ fallbackPlacements: ['top'] })] : []),
    ],
  });

  useEffect(() => {
    setFloatingFullStyles((style) => ({
      ...style,
      ...floatingStyles,
    }));
  }, [floatingStyles]);

  useMount(() => {
    if (autoFocus) {
      handleFocus();
    }
  });

  useClickAway(() => {
    hideSuggestion();
  }, refs.reference as React.MutableRefObject<HTMLDivElement>);

  const handleFocus = () => {
    input.current?.focus();
  };

  const handleCancelQuerySuggestion = () => {
    if (abortController) {
      abortController.abort('repeated request');
      setAbortController(undefined);
    }
  };

  const handleQuerySuggestion = (value: string) => {
    handleCancelQuerySuggestion();
    if (inputValue === latestKeyword) {
      showSuggestion();
      return;
    }
    const ac = new AbortController();
    setAbortController(ac);
    autocomplete
      .handleQueryData(value.trim(), api, ac)
      .then(({ data }) => {
        setLatestKeyword(value.trim());
        setSuggestions(data);
        showSuggestion('fetch', data);
        onFetch?.(data);
      })
      .catch((e: Error) => {
        if (e.name === 'AbortError') {
          onAbortFetch?.(e);
        }
      });
  };

  const { run: handleDebounceQuerySuggestion } = useDebounceFn(handleQuerySuggestion, {
    wait: queryDelay,
  });

  const handleInput = (event: React.ChangeEvent<HTMLInputElement>) => {
    hideSuggestion();
    const { value } = event.target;
    setInputValue(value);
    onInput?.(value);
    setKeyboardActiveIndex(undefined);
    setSelectSuggestion(undefined);
    if (value.length === 0) {
      clearSuggestion();
      return;
    }
    handleDebounceQuerySuggestion(value);
  };

  const handleInputClick = () => {
    if (inputValue) {
      handleQuerySuggestion(inputValue);
    } else if (historyEnabled) {
      setLatestKeyword('');
      handleShowHistory();
    }
  };

  const handleInputFocus = () => {
    onFocus?.();
  };

  const handleInputBlur = () => {
    onBlur?.();
  };

  const handleShowHistory = () => {
    const options = {
      enabled: historyEnabled,
      key: historyStorageKey,
      type: historyType,
    };
    const data = autocomplete.getHistory(options as autocomplete.Type.HistoryOptions);
    setSuggestions(data);
    showSuggestion('history', data);
  };

  const clearSuggestion = () => {
    setSuggestions([]);
  };

  const showSuggestion = (type = 'fetch', suggestions = getSuggestions()) => {
    if (suggestions.length === 0) {
      clearSuggestion();
      hideSuggestion();
      return;
    }
    setSuggestionType(type);
    if (suggestionVisible) {
      return;
    }
    setSuggestionVisible(true);
    onDropdownVisibleChange?.(true);
  };

  const hideSuggestion = () => {
    if (!suggestionVisible) {
      return;
    }
    setSuggestionVisible(false);
    onDropdownVisibleChange?.(false);
  };

  const handleSubmit = () => {
    onSubmit?.({
      text: inputValue,
    });
  };

  const handleInputClear = () => {
    setSelectSuggestion(undefined);
    setInputValue('');
    clearSuggestion();
    hideSuggestion();
    handleFocus();
    onClear?.();
  };

  const handleKeyDown = (event: React.KeyboardEvent<Element>) => {
    switch (event.key) {
      case 'Enter':
        if (!isUndefined(keyboardActiveIndex)) {
          handleSuggestionClick(suggestions[keyboardActiveIndex!]);
        }
        break;
      case 'ArrowUp':
        if (!keyboardActiveIndex) {
          setKeyboardActiveIndex(suggestions.length - 1);
        } else {
          setKeyboardActiveIndex(keyboardActiveIndex - 1);
        }
        backFill && handleFillInput();
        break;
      case 'ArrowDown':
        if (isUndefined(keyboardActiveIndex) || keyboardActiveIndex! >= suggestions.length - 1) {
          setKeyboardActiveIndex(0);
        } else {
          setKeyboardActiveIndex(keyboardActiveIndex! + 1);
        }
        backFill && handleFillInput();
        break;
      case 'Escape':
        handleInputClear();
        break;
    }
  };

  const handleFillInput = () => {
    setSelectSuggestion(suggestions[keyboardActiveIndex!]);
    setInputValue(removeHtmlTags(selectSuggestion!.name || ''));
  };

  const handleHistoryClear = (event: React.MouseEvent) => {
    const options = {
      key: historyStorageKey,
      type: historyType,
    };
    autocomplete.removeHistory(options as autocomplete.Type.HistoryOptions);
    clearSuggestion();
    hideSuggestion();
    event.preventDefault();
  };

  const handleSuggestionClick = (company: autocomplete.Type.CompanyDataType) => {
    setInputValue(removeHtmlTags(company.name));
    const selectSuggestionData = {
      id: company.id,
      name: company.name,
    };
    setSelectSuggestion(selectSuggestionData);
    clearSuggestion();
    hideSuggestion();
    if (historyEnabled && selectSuggestionData) {
      const options = {
        enabled: historyEnabled,
        key: historyStorageKey,
        type: historyType,
      };
      autocomplete.addHistory(selectSuggestionData, options as autocomplete.Type.HistoryOptions);
    }
    onSelect?.(selectSuggestionData);
  };

  return (
    <div
      ref={refs.setReference}
      className={clsx('company-autocomplete', {
        'company-autocomplete--show-submit': showSubmitButton,
        'company-autocomplete--words': inputValue.length > 0,
        'company-autocomplete--activated': suggestionVisible,
      })}
      onKeyDown={handleKeyDown}
    >
      <div className="company-autocomplete__input">
        <input
          ref={input}
          type="text"
          placeholder={placeholder}
          value={inputValue}
          onInput={handleInput}
          onClick={handleInputClick}
          onFocus={handleInputFocus}
          onBlur={handleInputBlur}
          aria-autocomplete="list"
          aria-labelledby={
            suggestionVisible && suggestions.length === 0 ? 'suggestion-no-results' : undefined
          }
        />
        {clearable && (
          <div className="company-autocomplete__clear">
            <i
              className="company-autocomplete__clear-icon"
              onClick={handleInputClear}
              dangerouslySetInnerHTML={{ __html: clearIcon }}
            />
          </div>
        )}
      </div>
      {showSubmitButton && (
        <div className="company-autocomplete__submit">
          <button type="button" onClick={handleSubmit}>
            {submitButtonLabel}
          </button>
        </div>
      )}
      <Suggestion>
        <div
          ref={refs.setFloating}
          style={floatingFullStyles}
          className={clsx('suggestion-popper', {
            'suggestion-popper--activated': suggestionVisible,
          })}
        >
          <div className="suggestion-popper__body">
            {suggestions.map((item, index) => (
              <div
                className={clsx('suggestion', {
                  'suggestion--keyboard-active': keyboardActiveIndex === index,
                })}
                key={item.id}
                onClick={() => handleSuggestionClick(item)}
              >
                <div className="suggestion__avatar">
                  {suggestionType === 'history' && (
                    <i
                      className="suggestion__avatar-icon"
                      dangerouslySetInnerHTML={{ __html: historyItemIcon }}
                    />
                  )}
                  {item.avatar && <img alt={item.id} src={item.avatar} />}
                </div>
                <div className="suggestion__label">{item.name}</div>
                <div className="suggestion__extra"></div>
              </div>
            ))}
          </div>
          {historyClearable && suggestionType === 'history' && (
            <div className="suggestion-popper__footer">
              <a href="#" onClick={handleHistoryClear}>
                <i
                  className="suggestion-popper__icon"
                  dangerouslySetInnerHTML={{ __html: historyClearIcon }}
                />
                删除历史
              </a>
            </div>
          )}
        </div>
      </Suggestion>
    </div>
  );
};

export default AutoComponent;
