// packages/vue/src/autocomplete.vue
<template>
  <div
    ref="reference"
    class="company-autocomplete"
    :class="[
      {
        'company-autocomplete--show-submit': showSubmitButton,
        'company-autocomplete--words': nativeInputValue.length > 0,
        'company-autocomplete--activated': suggestionVisible,
      },
    ]"
    v-click-outside="handleClickOutside"
    @keydown="handleKeyDown"
  >
    <div class="company-autocomplete__input">
      <input
        ref="input"
        type="text"
        v-bind="$attrs"
        :placeholder="placeholder"
        @input="handleInput"
        @click="handleInputClick"
        @focus="handleInputFocus"
        @blur="handleInputBlur"
      />
      <div v-if="clearable" class="company-autocomplete__clear">
        <i
          class="company-autocomplete__clear-icon i-ic-baseline-cancel"
          @click="handleInputClear"
        />
      </div>
    </div>
    <div v-if="showSubmitButton" class="company-autocomplete__submit">
      <button type="button" @click="handleSubmit">
        {{ submitButtonLabel }}
      </button>
    </div>
  </div>
  <Teleport to="body" :disabled="!popupAppendToBody" v-if="isVue3">
    <div
      ref="floating"
      class="suggestion-popper"
      :class="[
        {
          'suggestion-popper--activated': suggestionVisible,
        },
      ]"
      :style="floatingFullStyles"
    >
      <div class="suggestion-popper__body">
        <div
          class="suggestion"
          v-for="(item, index) in suggestions"
          :key="item.name"
          @click="handleSuggestionClick(item)"
          :class="[
            {
              'suggestion--keyboard-active': keyboardActiveIndex === index,
            },
          ]"
        >
          <div class="suggestion__avatar">
            <i
              class="suggestion__avatar-icon i-ic-baseline-history-toggle-off"
              v-if="suggestionType === 'history'"
            />
            <img :alt="item.id" :src="item.avatar" v-else-if="item.avatar" />
          </div>
          <div class="suggestion__label">
            {{ item.name }}
          </div>
          <div class="suggestion__extra"></div>
        </div>
      </div>
      <div
        class="suggestion-popper__footer"
        v-show="historyClearable && suggestionType === 'history'"
      >
        <a href="javascript:;" @click="handleHistoryClear">
          <i class="suggestion-popper__icon i-ic-baseline-auto-delete"></i>
          删除历史
        </a>
      </div>
    </div>
  </Teleport>
</template>

<script lang="ts">
  import {
    defineComponent,
    PropType,
    ref,
    Ref,
    onMounted,
    watch,
    computed,
    isVue3,
  } from 'vue-demi';
  import { autocomplete } from '@company-ui/core';
  import { debounce, removeHtmlTags, isUndefined, isNil } from '@company-ui/shared';
  import { useFloating, autoUpdate, offset, size, flip } from '@floating-ui/vue';
  import clickOutside from './directives/click-outside';

  export default defineComponent({
    name: 'Autocomplete',
    directives: {
      clickOutside,
    },
    props: {
      modelValue: {
        type: String,
        default: '',
      },
      api: {
        type: String as PropType<autocomplete.Type.ApiType>,
        default: 'clearbit',
      },
      queryDelay: {
        type: Number,
        default: 500,
      },
      placeholder: {
        type: String,
        default: '请输入企业名称或统一社会信用代码',
      },
      clearable: {
        type: Boolean,
        default: true,
      },
      backFill: {
        type: Boolean,
        default: false,
      },
      popupAppendToBody: {
        type: Boolean,
        default: true,
      },
      autoFocus: {
        type: Boolean,
        default: true,
      },
      showSubmitButton: {
        type: Boolean,
        default: true,
      },
      submitButtonLabel: {
        type: String,
        default: 'Submit',
      },
      offsetTop: {
        type: Number,
        default: 5,
      },
      autoFlip: {
        type: Boolean,
        default: false,
      },
      historyEnabled: {
        type: Boolean,
        default: true,
      },
      historyType: {
        type: String as PropType<autocomplete.Type.HistoryType>,
        default: 'localStorage',
      },
      historyStorageKey: {
        type: String,
        default: 'company-history',
      },
      historyClearable: {
        type: Boolean,
        default: true,
      },
    },
    emits: [
      'update:modelValue',
      'input',
      'fetch',
      'abortFetch',
      'select',
      'clear',
      'focus',
      'blur',
      'submit',
      'dropdownVisibleChange',
    ],
    setup(props, context) {
      let abortController: AbortController | undefined;
      let latestKeyword: string = '';
      const nativeInputValue = computed(() =>
        isNil(props.modelValue) ? '' : String(props.modelValue)
      );
      const selectSuggestion = ref() as Ref<autocomplete.Type.CompanyDataType | undefined>;
      const suggestionVisible = ref(false);
      const suggestionType = ref('fetch');
      const suggestions = ref([]) as Ref<autocomplete.Type.CompanyDataType[]>;
      const keyboardActiveIndex = ref();
      const reference = ref() as Ref<HTMLDivElement>;
      const floating = ref() as Ref<HTMLDivElement>;
      const input = ref() as Ref<HTMLInputElement>;
      const floatingWidth = ref() as Ref<string>;
      const { floatingStyles } = useFloating(reference, floating, {
        whileElementsMounted: autoUpdate,
        middleware: [
          offset(props.offsetTop),
          size({
            apply: ({ rects }) => {
              floatingWidth.value = `${rects.reference.width}px`;
            },
          }),
          ...(props.autoFlip
            ? [
                flip({
                  fallbackPlacements: ['top'],
                }),
              ]
            : []),
        ],
      });

      onMounted(() => {
        if (props.autoFocus) {
          input.value?.focus();
        }
        setNativeInputValue();
      });

      watch(nativeInputValue, () => setNativeInputValue());

      const floatingFullStyles = computed(() => {
        return {
          ...floatingStyles.value,
          width: floatingWidth.value,
        };
      });

      const handleCancelQuerySuggestion = () => {
        if (abortController) {
          abortController.abort('repeated request');
          abortController = undefined;
        }
      };

      const handleQuerySuggestion = async (value: string) => {
        handleCancelQuerySuggestion();
        if (nativeInputValue.value === latestKeyword) {
          showSuggestion();
          return;
        }
        abortController = new AbortController();
        autocomplete
          .handleQueryData(value.trim(), props.api as string, abortController)
          .then(({ data }) => {
            latestKeyword = value.trim();
            suggestions.value = data;
            showSuggestion();
            context.emit('fetch', data);
          })
          .catch((e) => {
            if (e.name === 'AbortError') {
              context.emit('abortFetch', e);
            }
          });
      };

      const handleDebounceQuerySuggestion = debounce((value: string) => {
        handleQuerySuggestion(value);
      }, props.queryDelay);

      const setNativeInputValue = () => {
        if (input.value.value === nativeInputValue.value) {
          return;
        }
        input.value.value = nativeInputValue.value;
      };

      const handleInput = (event: Event) => {
        hideSuggestion();
        const { value } = event.target as HTMLInputElement;
        context.emit('update:modelValue', value);
        context.emit('input', value);
        keyboardActiveIndex.value = undefined;
        selectSuggestion.value = undefined;
        if (value.length === 0) {
          clearSuggestion();
          return;
        }
        handleDebounceQuerySuggestion(value);
      };

      const handleInputClick = () => {
        if (nativeInputValue.value) {
          handleQuerySuggestion(nativeInputValue.value);
        } else if (props.historyEnabled) {
          latestKeyword = '';
          handleShowHistory();
        }
      };

      const handleInputFocus = () => {
        context.emit('focus');
      };

      const handleInputBlur = () => {
        handleCancelQuerySuggestion();
        context.emit('blur');
      };

      const handleShowHistory = () => {
        suggestions.value = autocomplete.getHistory({
          enabled: props.historyEnabled,
          key: props.historyStorageKey,
          type: props.historyType,
        } as autocomplete.Type.HistoryOptions);
        showSuggestion('history');
      };

      const clearSuggestion = () => {
        suggestions.value = [];
      };

      const showSuggestion = (type = 'fetch') => {
        if (suggestions.value.length === 0) {
          clearSuggestion();
          hideSuggestion();
          return;
        }
        suggestionType.value = type;
        if (suggestionVisible.value) {
          return;
        }
        suggestionVisible.value = true;
        context.emit('dropdownVisibleChange', true);
      };

      const hideSuggestion = () => {
        if (!suggestionVisible.value) {
          return;
        }
        suggestionVisible.value = false;
        context.emit('dropdownVisibleChange', false);
      };

      const handleSubmit = () => {
        context.emit('submit', {
          text: nativeInputValue.value,
        });
      };

      const handleInputClear = () => {
        selectSuggestion.value = undefined;
        context.emit('update:modelValue', '');
        clearSuggestion();
        context.emit('clear');
      };

      const handleClickOutside = () => {
        hideSuggestion();
      };

      const handleKeyDown = (event: KeyboardEvent) => {
        switch (event.key) {
          case 'Enter':
            if (!isUndefined(keyboardActiveIndex.value)) {
              handleSuggestionClick(suggestions.value[keyboardActiveIndex.value]);
            }
            break;
          case 'ArrowUp':
            if (!keyboardActiveIndex.value) {
              keyboardActiveIndex.value = suggestions.value.length - 1;
            } else {
              keyboardActiveIndex.value--;
            }
            props.backFill && handleFillInput();
            break;
          case 'ArrowDown':
            if (
              isUndefined(keyboardActiveIndex.value) ||
              keyboardActiveIndex.value >= suggestions.value.length - 1
            ) {
              keyboardActiveIndex.value = 0;
            } else {
              keyboardActiveIndex.value++;
            }
            props.backFill && handleFillInput();
            break;
          case 'Escape':
            handleInputClear();
            break;
        }
      };

      const handleFillInput = () => {
        selectSuggestion.value = suggestions.value[keyboardActiveIndex.value];
        context.emit('update:modelValue', removeHtmlTags(selectSuggestion.value?.name || ''));
      };

      const handleHistoryClear = () => {
        autocomplete.removeHistory({
          key: props.historyStorageKey,
          type: props.historyType,
        } as autocomplete.Type.HistoryOptions);
        clearSuggestion();
        hideSuggestion();
      };

      const handleSuggestionClick = (company: autocomplete.Type.CompanyDataType) => {
        context.emit('update:modelValue', removeHtmlTags(company.name));
        selectSuggestion.value = {
          id: company.id,
          name: company.name,
        };
        clearSuggestion();
        hideSuggestion();
        if (props.historyEnabled && selectSuggestion) {
          autocomplete.addHistory(selectSuggestion.value!, {
            enabled: props.historyEnabled,
            key: props.historyStorageKey,
            type: props.historyType,
          } as autocomplete.Type.HistoryOptions);
        }
        context.emit('select', selectSuggestion.value);
      };
      return {
        nativeInputValue,
        reference,
        floating,
        input,
        floatingFullStyles,
        suggestions,
        suggestionType,
        suggestionVisible,
        handleClickOutside,
        handleKeyDown,
        handleInput,
        handleInputClick,
        handleInputFocus,
        handleInputBlur,
        handleSubmit,
        handleInputClear,
        handleHistoryClear,
        handleSuggestionClick,
        keyboardActiveIndex,
        isVue3,
      };
    },
  });
</script>

// packages/react/src/autocomplete/index.tsx
import React, { useState, useRef, useEffect } from 'react';
import clsx from 'clsx';
import { useMount, useClickAway, useDebounceFn, useGetState, useControllableValue } from 'ahooks';
import { autocomplete } from '@company-ui/core';
import { isUndefined, removeHtmlTags } from '@company-ui/shared';
import { FloatingPortal, useFloating, autoUpdate, offset, size, flip } from '@floating-ui/react';

export type AutoCompleteProps = {
  defaultValue?: string;
  value?: string;
  api?: string;
  queryDelay?: number;
  placeholder?: string;
  clearable?: boolean;
  backFill?: boolean;
  popupAppendToBody?: boolean;
  autoFocus?: boolean;
  showSubmitButton?: boolean;
  submitButtonLabel?: string;
  offsetTop?: number;
  autoFlip?: boolean;
  historyEnabled?: boolean;
  historyType?: autocomplete.Type.HistoryType;
  historyStorageKey?: string;
  historyClearable?: boolean;
  onInput?: (_value: string) => void;
  onFetch?: (_data: autocomplete.Type.CompanyDataType[]) => void;
  onAbortFetch?: (_e: Error) => void;
  onSelect?: (_data: autocomplete.Type.CompanyDataType) => void;
  onClear?: () => void;
  onFocus?: () => void;
  onBlur?: () => void;
  onSubmit?: (_args: { text: string }) => void;
  onDropdownVisibleChange?: (_state: boolean) => void;
};

const SuggestionComponent = {
  default: React.Fragment,
  portal: FloatingPortal,
};

const AutoComponent: React.FC<AutoCompleteProps> = (props) => {
  const {
    api = 'clearbit',
    queryDelay = 500,
    placeholder = '请输入企业名称或统一社会信用代码',
    clearable = true,
    backFill = false,
    popupAppendToBody = true,
    autoFocus = true,
    showSubmitButton = true,
    submitButtonLabel = 'Submit',
    offsetTop = 5,
    autoFlip = false,
    historyEnabled = true,
    historyType = 'localStorage',
    historyStorageKey = 'company-history',
    historyClearable = true,
    onInput,
    onFetch,
    onAbortFetch,
    onSelect,
    onClear,
    onFocus,
    onBlur,
    onSubmit,
    onDropdownVisibleChange,
  } = props;

  const clearIcon = autocomplete.initialOptions.clearIcon;
  const historyClearIcon = autocomplete.initialOptions.history.clearIcon;
  const historyItemIcon = autocomplete.initialOptions.history.itemIcon;
  const Suggestion = SuggestionComponent[popupAppendToBody ? 'portal' : 'default'];

  const [inputValue, setInputValue] = useControllableValue<string>(props);
  const [abortController, setAbortController] = useState<AbortController>();
  const [latestKeyword, setLatestKeyword] = useState('');
  const [selectSuggestion, setSelectSuggestion] = useState<autocomplete.Type.CompanyDataType>();
  const [suggestionVisible, setSuggestionVisible] = useState(false);
  const [suggestionType, setSuggestionType] = useState('fetch');
  const [suggestions, setSuggestions, getSuggestions] = useGetState<
    autocomplete.Type.CompanyDataType[]
  >([]);
  const [keyboardActiveIndex, setKeyboardActiveIndex] = useState<number>();
  const [floatingFullStyles, setFloatingFullStyles] = useState<React.CSSProperties>();
  const input = useRef<HTMLInputElement>(null);
  const { refs, floatingStyles } = useFloating({
    whileElementsMounted: autoUpdate,
    middleware: [
      offset(offsetTop),
      size({
        apply: ({ rects }) => {
          setFloatingFullStyles((style) => ({
            ...style,
            width: `${rects.reference.width}px`,
          }));
        },
      }),
      ...(autoFlip ? [flip({ fallbackPlacements: ['top'] })] : []),
    ],
  });

  useEffect(() => {
    setFloatingFullStyles((style) => ({
      ...style,
      ...floatingStyles,
    }));
  }, [floatingStyles]);

  useMount(() => {
    if (autoFocus) {
      handleFocus();
    }
  });

  useClickAway(() => {
    hideSuggestion();
  }, refs.reference as React.MutableRefObject<HTMLDivElement>);

  const handleFocus = () => {
    input.current?.focus();
  };

  const handleCancelQuerySuggestion = () => {
    if (abortController) {
      abortController.abort('repeated request');
      setAbortController(undefined);
    }
  };

  const handleQuerySuggestion = (value: string) => {
    handleCancelQuerySuggestion();
    if (inputValue === latestKeyword) {
      showSuggestion();
      return;
    }
    const ac = new AbortController();
    setAbortController(ac);
    autocomplete
      .handleQueryData(value.trim(), api, ac)
      .then(({ data }) => {
        setLatestKeyword(value.trim());
        setSuggestions(data);
        showSuggestion('fetch', data);
        onFetch?.(data);
      })
      .catch((e: Error) => {
        if (e.name === 'AbortError') {
          onAbortFetch?.(e);
        }
      });
  };

  const { run: handleDebounceQuerySuggestion } = useDebounceFn(handleQuerySuggestion, {
    wait: queryDelay,
  });

  const handleInput = (event: React.ChangeEvent<HTMLInputElement>) => {
    hideSuggestion();
    const { value } = event.target;
    setInputValue(value);
    onInput?.(value);
    setKeyboardActiveIndex(undefined);
    setSelectSuggestion(undefined);
    if (value.length === 0) {
      clearSuggestion();
      return;
    }
    handleDebounceQuerySuggestion(value);
  };

  const handleInputClick = () => {
    if (inputValue) {
      handleQuerySuggestion(inputValue);
    } else if (historyEnabled) {
      setLatestKeyword('');
      handleShowHistory();
    }
  };

  const handleInputFocus = () => {
    onFocus?.();
  };

  const handleInputBlur = () => {
    onBlur?.();
  };

  const handleShowHistory = () => {
    const options = {
      enabled: historyEnabled,
      key: historyStorageKey,
      type: historyType,
    };
    const data = autocomplete.getHistory(options as autocomplete.Type.HistoryOptions);
    setSuggestions(data);
    showSuggestion('history', data);
  };

  const clearSuggestion = () => {
    setSuggestions([]);
  };

  const showSuggestion = (type = 'fetch', suggestions = getSuggestions()) => {
    if (suggestions.length === 0) {
      clearSuggestion();
      hideSuggestion();
      return;
    }
    setSuggestionType(type);
    if (suggestionVisible) {
      return;
    }
    setSuggestionVisible(true);
    onDropdownVisibleChange?.(true);
  };

  const hideSuggestion = () => {
    if (!suggestionVisible) {
      return;
    }
    setSuggestionVisible(false);
    onDropdownVisibleChange?.(false);
  };

  const handleSubmit = () => {
    onSubmit?.({
      text: inputValue,
    });
  };

  const handleInputClear = () => {
    setSelectSuggestion(undefined);
    setInputValue('');
    clearSuggestion();
    hideSuggestion();
    handleFocus();
    onClear?.();
  };

  const handleKeyDown = (event: React.KeyboardEvent<Element>) => {
    switch (event.key) {
      case 'Enter':
        if (!isUndefined(keyboardActiveIndex)) {
          handleSuggestionClick(suggestions[keyboardActiveIndex!]);
        }
        break;
      case 'ArrowUp':
        if (!keyboardActiveIndex) {
          setKeyboardActiveIndex(suggestions.length - 1);
        } else {
          setKeyboardActiveIndex(keyboardActiveIndex - 1);
        }
        backFill && handleFillInput();
        break;
      case 'ArrowDown':
        if (isUndefined(keyboardActiveIndex) || keyboardActiveIndex! >= suggestions.length - 1) {
          setKeyboardActiveIndex(0);
        } else {
          setKeyboardActiveIndex(keyboardActiveIndex! + 1);
        }
        backFill && handleFillInput();
        break;
      case 'Escape':
        handleInputClear();
        break;
    }
  };

  const handleFillInput = () => {
    setSelectSuggestion(suggestions[keyboardActiveIndex!]);
    setInputValue(removeHtmlTags(selectSuggestion!.name || ''));
  };

  const handleHistoryClear = (event: React.MouseEvent) => {
    const options = {
      key: historyStorageKey,
      type: historyType,
    };
    autocomplete.removeHistory(options as autocomplete.Type.HistoryOptions);
    clearSuggestion();
    hideSuggestion();
    event.preventDefault();
  };

  const handleSuggestionClick = (company: autocomplete.Type.CompanyDataType) => {
    setInputValue(removeHtmlTags(company.name));
    const selectSuggestionData = {
      id: company.id,
      name: company.name,
    };
    setSelectSuggestion(selectSuggestionData);
    clearSuggestion();
    hideSuggestion();
    if (historyEnabled && selectSuggestionData) {
      const options = {
        enabled: historyEnabled,
        key: historyStorageKey,
        type: historyType,
      };
      autocomplete.addHistory(selectSuggestionData, options as autocomplete.Type.HistoryOptions);
    }
    onSelect?.(selectSuggestionData);
  };

  return (
    <div
      ref={refs.setReference}
      className={clsx('company-autocomplete', {
        'company-autocomplete--show-submit': showSubmitButton,
        'company-autocomplete--words': inputValue.length > 0,
        'company-autocomplete--activated': suggestionVisible,
      })}
      onKeyDown={handleKeyDown}
    >
      <div className="company-autocomplete__input">
        <input
          ref={input}
          type="text"
          placeholder={placeholder}
          value={inputValue}
          onInput={handleInput}
          onClick={handleInputClick}
          onFocus={handleInputFocus}
          onBlur={handleInputBlur}
          aria-autocomplete="list"
          aria-labelledby={
            suggestionVisible && suggestions.length === 0 ? 'suggestion-no-results' : undefined
          }
        />
        {clearable && (
          <div className="company-autocomplete__clear">
            <i
              className="company-autocomplete__clear-icon"
              onClick={handleInputClear}
              dangerouslySetInnerHTML={{ __html: clearIcon }}
            />
          </div>
        )}
      </div>
      {showSubmitButton && (
        <div className="company-autocomplete__submit">
          <button type="button" onClick={handleSubmit}>
            {submitButtonLabel}
          </button>
        </div>
      )}
      <Suggestion>
        <div
          ref={refs.setFloating}
          style={floatingFullStyles}
          className={clsx('suggestion-popper', {
            'suggestion-popper--activated': suggestionVisible,
          })}
        >
          <div className="suggestion-popper__body">
            {suggestions.map((item, index) => (
              <div
                className={clsx('suggestion', {
                  'suggestion--keyboard-active': keyboardActiveIndex === index,
                })}
                key={item.id}
                onClick={() => handleSuggestionClick(item)}
              >
                <div className="suggestion__avatar">
                  {suggestionType === 'history' && (
                    <i
                      className="suggestion__avatar-icon"
                      dangerouslySetInnerHTML={{ __html: historyItemIcon }}
                    />
                  )}
                  {item.avatar && <img alt={item.id} src={item.avatar} />}
                </div>
                <div className="suggestion__label">{item.name}</div>
                <div className="suggestion__extra"></div>
              </div>
            ))}
          </div>
          {historyClearable && suggestionType === 'history' && (
            <div className="suggestion-popper__footer">
              <a href="#" onClick={handleHistoryClear}>
                <i
                  className="suggestion-popper__icon"
                  dangerouslySetInnerHTML={{ __html: historyClearIcon }}
                />
                删除历史
              </a>
            </div>
          )}
        </div>
      </Suggestion>
    </div>
  );
};

export default AutoComponent;
